### ISSUE TITLE
Snap lines missing from 2.10.0

### ISSUE THREAD

**Issue by CaelanO** [chrislo27/RhythmHeavenRemixEditor2#100]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The snap lines do not appear anymore, instead invisible on the three different palettes

### Steps to Reproduce the Problem
1. Open either run_windows or run_windows_doNotLazyLoad
2. Drag any cue into the 5 bars.

**Expected behavior:** The snap bars that would tell you how far into a beat you are appear

**Actual behavior:** They do not appear, so you are left to guess where exactly you placed it.

**Stacktrace/error log:** 
[log_2017-03-31_11-53-41.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/886628/log_2017-03-31_11-53-41.txt)

**Version affected:** 2.10.0

**Comment by chrislo27** [comment]
Fixed, will release v2.10.1 shortly.
