### ISSUE TITLE
Feature Request - Quick Song-Mute Button

### ISSUE THREAD

**Issue by Strawzzboy64** [chrislo27/RhythmHeavenRemixEditor2#101]
(Since this is not a bug, I deleted all the stuff where you fill out info. I hope this is ok. That said, the version for this request is 2.10.1)

I was wondering if there could be a button that mutes or un-mutes the chosen song. And if the button could be right next to the music select button.

**Comment by chrislo27** [comment]
Added for v2.10.2.
