### ISSUE TITLE
Frog Hop Spin it Boys extra sfx

### ISSUE THREAD

**Issue by Strawzzboy64** [chrislo27/RhythmHeavenRemixEditor2#107]
### Prerequisites
* [ ] This issue specifically has something to do with RHRE2
* [ ] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
In the Frog Hop "Spin it Boys" cue, there is an extra "shake" sfx at the end. Specifically in the cue - "spin it boys - backup - boys"

### Steps to Reproduce the Problem
1. Place the Frog Hop cue: "spin it boys - backup - boys"
2. Play the remix.

**Expected behavior:** 
"spin it boys - backup - boys" cue should sound without an extra "shake" sfx at the end.

**Actual behavior:** 
"spin it boys - backup - boys" cue has an extra "shake" sfx at the end.

**Stacktrace/error log:** 
n/a 

**Version affected:** 
2.10.1

### Additional Information
I think this is just a matter of cutting the shake sfx out of the "spin it boys - backup - boys" sfx.

**Comment by chrislo27** [comment]
Fixed for `v2.10.2`. Thank you for the fix!
