### ISSUE TITLE
Remix 7 Tap Trial needs a better icon

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#111]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The placeholder icon that I put for Remix 7 Tap Trial is still there. I wanted it to be replaced by a better icon.

**Comment by chrislo27** [comment]
Replaced with https://raw.githubusercontent.com/chrislo27/RhythmHeavenRemixEditor2/d608e958c43a07d8e1d3dd764a9044f53fbbda81/core/assets/sounds/cues/tapTrialRemix7/icon.png
