### ISSUE TITLE
How do I find the run_windows.bat file

### ISSUE THREAD

**Issue by CalluwanaImp** [chrislo27/RhythmHeavenRemixEditor2#113]
I want to open the file, I have java 8 installed and have downloaded the files, but I can't find the run_windows.bat file that is needed to open the software.

**Comment by chrislo27** [comment]
It should be bundled. Screenshot your file directory with the jar file etc

**Comment by CalluwanaImp** [comment]
Here is what I've got.
![2017-04-11](https://cloud.githubusercontent.com/assets/27236374/24898828/109de89e-1e96-11e7-8639-3ae7b1bbb8a6.png)

**Comment by chrislo27** [comment]
Releases tab, download the jar. Never click Clone or Download unless you
know what you're doing.
