### ISSUE TITLE
You merged a minute too early

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#115]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
I was GOING to put one more commit, but then you merged it early!

### Additional Information
This is the commit I wanted to merge. https://github.com/GuardedLolz/RhythmHeavenRemixEditor2/commit/6aa31e8bce6627fa4d7555b8cad5d622c98f7a14

**Comment by chrislo27** [comment]
pls

**Comment by GuardedLolz** [comment]
wut

**Comment by chrislo27** [comment]
Can you please join this Discord server - I'd like to discuss this issue with you more fluently. https://discord.gg/kvzRyCA

**Comment by chrislo27** [comment]
I disagree with that change. Listening to Packing Pests 2, your original placement (at 165 BPM which is the BPM of PP2) sounds smoother and more like the original.

**Comment by GuardedLolz** [comment]
Go see the real PP2 and you'll see that the new placement is correct.
