### ISSUE TITLE
RHRE2 needs to have the ability to be pinned in taskbar

### ISSUE THREAD

**Issue by Armodillomatt12** [chrislo27/RhythmHeavenRemixEditor2#123]
It will be easier to open the application without going into the folder. this will mostly be helpful if the folder you put RHRE2 in is filled with your other stuff like if it's gonna be in a new season of hoarders.

**Comment by chrislo27** [comment]
https://superuser.com/questions/257467/windows-7-how-to-pin-a-jar-to-the-taskbar
