### ISSUE TITLE
It don't see how you transfer the remix to audio.......there's no real way to share my remix.

### ISSUE THREAD

**Issue by SariothePlumber** [chrislo27/RhythmHeavenRemixEditor2#126]
### Prerequisites
* [ ] This issue specifically has something to do with RHRE2
* [ ] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
[insert description of the issue]

### Steps to Reproduce the Problem
1. [First step]
2. [Second step]

**Expected behavior:** [insert what was supposed to happen here]

**Actual behavior:** [insert what actually happened here]

**Stacktrace/error log:** [attach the log file from `logs/log_YYYY-MM-DD_HH-MM-SS.txt here]

**Version affected:** [insert the version of RHRE2 here]

### Additional Information
[insert any other information that may be able to help me with the problem here]

**Comment by GlitchyPSIX** [comment]
_this is completely empty not to mention it's not a real program issue_ 😒
ok i'll just say one thing, use audacity to record RHRE2
you google the rest.

**Comment by SariothePlumber** [comment]
Yeah, sorry about that. It was a problem though. For I didn't know how to record it. But thanks for the advice.
