### ISSUE TITLE
Sounds not playing?

### ISSUE THREAD

**Issue by YoshiUK** [chrislo27/RhythmHeavenRemixEditor2#127]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
For some reason, there are certain sounds that don't play when added into the custom remix editor on my version, such as the Spaceball sounds, the Fillbots filling cue, or the Karate Man (Wii)'s "Hit 3!" cue. Instead, playing them disables the left speaker for the duration that they are playing. They sound fine in Audacity and no one else appears to have this problem, so what's going on?

### Steps to Reproduce the Problem
1. Be me
2. Insert the following cues into the editor:
All Bon Odori cues (except for don 1)
Bouncy Road snort cue
Both Clappy Trio cues
Karate Man (GBA) pot break cue
Both Ninja Bodyguard cues
Night Walk (GBA) "wot" cue
Half of the Rap Men cues (desu ka, kamone and saiko are all affected)
Space Gramps (Space Dance) Japanese cues
Spaceball's hit and shoot cues
Fillbots filling sound
Glee Club baton lift cue
Karate Man (Wii) Hit 3 cue
The Skill Star Cue

**Expected behavior:**
The cues would play properly
**Actual behavior:**
The left speaker got disabled for the time the cue played
**Stacktrace/error log:** 
No error log
**Version affected:** 
v2.10.3 and lower, but Karate Man (Wii) "Hit 3" wasn't affected before I got 2.10.3
### Additional Information
Audacity plays the files fine, it's only in the editor that the fault occurs.

**Comment by chrislo27** [comment]
In sound settings, is the editor set to use mono sound only?

**Comment by YoshiUK** [comment]
Where are the sound settings?

**Comment by chrislo27** [comment]
On your computer.

**Comment by YoshiUK** [comment]
Then it should be fine since everything else works normally...
