### ISSUE TITLE
So the tempo isn't particularly working for me...

### ISSUE THREAD

**Issue by Minebot45** [chrislo27/RhythmHeavenRemixEditor2#130]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue) already (not really)

### Description
So for whatever reason, my copy has the tempo locked at 120 BPM, even if I use the tapalong to try changing it to something else. The only way around this that I've found is to put a tempo change immediately at the start of the song.

### Steps to Reproduce the Problem
1. Load the song I want to use
2. Go to the tapalong and tap, say, 180 BPM
3. Put something into the editor

**Expected behavior:** The staff moves at 180 BPM.

**Actual behavior:** The staff moves at 120 BPM.

**Stacktrace/error log:** ...erm, I didn't think I had to create an error log (I've got barely any programming experience).

**Version affected:** v2.10.5

### Additional Information
I got the song I tried using from a YouTube video (I used a YT-to-MP3 converter site) has a slight gap between the start of the file and the start of the song. This has less to do with the software and more to do with me.

**Comment by chrislo27** [comment]
The tapalong is only used to help you determine a tempo. It doesn't do any setting for you.

This is as intended and will be closed. The log files can be found in the logs folder which is at the root directory of the jar file for future reference.
