### ISSUE TITLE
Add Marchers 2 sfx (only JP)

### ISSUE THREAD

**Issue by Jacobgharibian** [chrislo27/RhythmHeavenRemixEditor2#144]
Add the sfx 
Attention march
Marching
Right Head Turn
Fast Right Head Turn
Left Head Turn 
Fast Left Turn
Attention Halt

**Comment by GuardedLolz** [comment]
I'll get around to it.

**Comment by Miracle22s** [comment]
I might as well get them those, too. And I'll add Remix 7 8 variant with space bunnies.

**Comment by Miracle22s** [comment]
Issuw fixed, and it has been added.
