### ISSUE TITLE
The SFX database shouldn't be bundled with the editor

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor2#145]
It should really be dynamically updatable so people don't have to redownload 50 MB of editor each time.

The versioning scheme for this would be weird though (technically it would start at v1.0.0 but then people will undoubtedly get confused).

**Comment by Sorurus** [comment]
Support

**Comment by chrislo27** [comment]
The nature of the GitHub (v3) API makes this very request-intensive and would be hard to integrate into the current editor. One also has to account for partial databases (interrupted downloads) and I think this would theoretically be better off using Git itself (where the database is on another repository).

This should be considered for RHRE3 though, if it happens.
