### ISSUE TITLE
Marching Orders should be split into its Tengoku and Megamix versions in the future

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#146]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Are these Megamix? And if they are, Do the fast face turn sounds have any sort of equivalent in the English language setting?

**Comment by chrislo27** [comment]
If RHRE2 currently doesn't have the separate game equivalent sounds between versions (ie: Tengoku and Megamix) then any version is acceptable and it will be put in the series where the game first appeared.

Once we get the separate sounds then the newer version can be put in the appropriate category.

**Comment by GuardedLolz** [comment]
I've done further research, and yes, these sounds are Megamix. Even the fast face turns. Now this is less about "these sounds are Megamix" and more about "we need the English fast face turns".

**Comment by Miracle22s** [comment]
Um, the english version doesn't have fast right face and left face turns. They are in Japanese in the files.

**Comment by GuardedLolz** [comment]
How do you know they didn't dub that?

**Comment by Miracle22s** [comment]
Cause I checked the debug files.

**Comment by GuardedLolz** [comment]
Can I see?

**Comment by Miracle22s** [comment]
do you have a discord account?

**Comment by GuardedLolz** [comment]
Yeah.

**Comment by Miracle22s** [comment]
what name?

**Comment by GuardedLolz** [comment]
GuardedLolz

**Comment by Miracle22s** [comment]
can you add me as a friend?

**Comment by Miracle22s** [comment]
what's you discord number?

**Comment by GuardedLolz** [comment]
Yes.

**Comment by Miracle22s** [comment]
DM me.

**Comment by GuardedLolz** [comment]
1429.

**Comment by Miracle22s** [comment]
I sent a friend invitation.

**Comment by Miracle22s** [comment]
wanna help you with Marching Orders GBA,, Lolz?
