### ISSUE TITLE
Fireworks sound increasing or decreasing in pitch with BPM.

### ISSUE THREAD

**Issue by Lvl100Feraligatr** [chrislo27/RhythmHeavenRemixEditor2#148]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already (I found a thread about the same thing happening to Bouncy Road https://github.com/chrislo27/RhythmHeavenRemixEditor2/issues/142)

### Description
If you use a "Rhythm Rocket" sound and increase the BPM, the pitch goes up. If you decrease it, it goes down. This shouldn't be happening because in Tengoku Remix 5, the BPM is 203, but the pitch of the Rhythm Rockets is completely normal.

### Steps to Reproduce the Problem
1. Place down a "Rhythm Rocket"
2. Increase BPM to, say, 170, and listen to the now increased pitch of the sound. Try setting the BPM to, say, 80, and listen to the decreased pitch of the sound.

**Expected behavior:** The firework sounds faster or slower without changing pitch.

**Actual behavior:** It played the sound faster or slower but increased or decreased pitch.

**Stacktrace/error log:** Not sure if this is necessary

**Version affected:** 2.13.0

### Additional Information
None

**Comment by chrislo27** [comment]
Fixed for `v2.13.1`.
