### ISSUE TITLE
Rhythm heaven remix editor 2 won't open

### ISSUE THREAD

**Issue by RhythmChan64** [chrislo27/RhythmHeavenRemixEditor2#150]
RHRE.jar won't open on my computer. I tried to open run_windows.bat and run_windows_doNotLazyLoad.bat. but it won't open on my windows 10. what should i do?

**Comment by chrislo27** [comment]
Why did you remove the issue template? If you filled it out it would have important information for me to help debug this problem. Instead, just saying "it doesn't work" is aggravating and annoying.

Please include your most recent log file. You can find it in the logs/ folder. If there is none, screenshot the terminal.

**Comment by RhythmChan64** [comment]
![capture](https://user-images.githubusercontent.com/29366080/27019124-9d5e5884-4eea-11e7-9fd5-b24c45ef54c7.PNG)

**Comment by chrislo27** [comment]
Also, ensure you have installed [Java 8](https://www.java.com/en/download/). It is required to run this program, as it states on the front page.

**Comment by chrislo27** [comment]
Update your graphics driver. It is possible your graphics card (integrated or not) does not support OpenGL 2.X.

**Comment by chrislo27** [comment]
Please try this launch option:
`java -jar -Dfile.encoding=UTF-8 RHRE.jar -softwaremode 0`

**Comment by GlitchyPSIX** [comment]
Windows 10, right?
Are you in Anniversary Update (v1607) or Creators Update (v1703, latest)?

**Comment by chrislo27** [comment]
Please try [`v2.14.1`](https://github.com/chrislo27/RhythmHeavenRemixEditor2/releases/tag/v2.14.1).

**Comment by xShadowKitsune** [comment]
![Andysnap_002](https://user-images.githubusercontent.com/51388113/66446365-3fae1a00-ea18-11e9-996a-9c219ff0c8da.png)

I haven't gotten this to work no matter what I did.
