### ISSUE TITLE
2.14.3 crash error

### ISSUE THREAD

**Issue by enxa217** [chrislo27/RhythmHeavenRemixEditor2#151]
Well, i always wanted to create a custom rmeix, but when i open it (no matter what method, it'll crash) it starts but when the program loads it closes automaticlly, i don't know why, i tried a older version, but when i hit esc. to continue, it closes.
So, i wanted a solution for this issue. Thanks

(https://user-images.githubusercontent.com/29504272/27253298-088bd02e-5372-11e7-887c-866fdfc5f7bf.jpg)

**Comment by GlitchyPSIX** [comment]
why was the issue template deleted

That seems to be an error with Windows 10 users running Creators Update while having GodMode or a file with an invalid name in the desktop.

If you have a file with an invalid name/blank name/GodMode shortcut in your desktop, try changing its name. (in the case of GodMode, delete it)

**Comment by enxa217** [comment]
Wow, thank you! It worked :D
