### ISSUE TITLE
Add Fireworks count-ins

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#152]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
I don't have the sounds myself (particularly the "go" sound), so yeah.

**Comment by Miracle22s** [comment]
I have those count-ins for Fireworks, and I'm willing to add these.

**Comment by GuardedLolz** [comment]
Okay!
