### ISSUE TITLE
Incorrect Home Run Cue

### ISSUE THREAD

**Issue by iRonnoc5** [chrislo27/RhythmHeavenRemixEditor2#155]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The cue for Home Run hit in Exhibition Match (both Megamix and Fever) have the name "stance," which is the name given to the cue for when the pitcher stances.
### Steps to Reproduce the Problem
1. Go to either version of Exhibition Match
2. Place the lowest "cue: Stance" onto the editor, and it will play the hit for the home run.

**Expected behavior:** The cue should be named something along the lines of "Home Run hit"

**Actual behavior:** The cue is named "stance"

**Stacktrace/error log:** 
[log_2017-06-21_22-17-47.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/1093610/log_2017-06-21_22-17-47.txt)

**Version affected:** 2.15.0, although most likely 2.15.2 as well.

### Additional Information
Not really sure how to go further in depth about this, apologies.

**Comment by chrislo27** [comment]
Please edit your issue to correctly have the issue template or I will ignore this issue.

**Comment by chrislo27** [comment]
Fixed for the next update. Thank you for your report.
