### ISSUE TITLE
We need better language instructions

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#157]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Specifically, what sounds should we put in a game language?

**Comment by Miracle22s** [comment]
Hm... Maybe it's best to consider in it a little before doing that.

**Comment by chrislo27** [comment]
Look at any language-based game. They contain every sound required, including duplicates.

Please close this issue when you feel you have gathered enough information.

**Comment by GuardedLolz** [comment]
Okay.
