### ISSUE TITLE
A little help...

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#159]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The "two" cue is supposed to be called "count in - two"

**Comment by Miracle22s** [comment]
I never noticed it.

**Comment by chrislo27** [comment]
Your personal preference is not an "issue". Please discuss these changes on Discord next time instead of occupying an entire issue number.

**Comment by chrislo27** [comment]
You also didn't state which game it was from, so I assumed it was the count-ins. In which case they were already fine, so I closed this issue. If you make a comment regarding which game it should be, you may reopen this issue.

**Comment by GuardedLolz** [comment]
Tunnel.

**Comment by chrislo27** [comment]
Fixed. Please be more descriptive in your issues next time.
