### ISSUE TITLE
No Looping or Playlisting (Kinda a suggestion in a way)

### ISSUE THREAD

**Issue by UltraGamesYT** [chrislo27/RhythmHeavenRemixEditor2#162]
I know it sounds like more of a request, but still, there should've been a looping button to loop your song once its over and a playlisting button so you can make folders of your remixes so you can listen to them. I think that'd be nice to have.

**Comment by chrislo27** [comment]
This issue is invalid if it doesn't use the template. Deleting the template shows you are lazy about suggestions/bugs and is a waste of my time to read.
