### ISSUE TITLE
(this request is invalid, please delete it) - [feature request] Allow selecting between games/cues while a remix is playing

### ISSUE THREAD

**Issue by Strawzzboy64** [chrislo27/RhythmHeavenRemixEditor2#163]
I would like to be able to move through the different games/cues while a remix is playing. I think placing cues while a remix is playing should still be disabled though.

**Comment by GuardedLolz** [comment]
Bam. Invalid.

**Comment by Miracle22s** [comment]
Bam! Does not invalid.
