### ISSUE TITLE
Allow selection between games and cues/sfx while a remix is playing

### ISSUE THREAD

**Issue by Strawzzboy64** [chrislo27/RhythmHeavenRemixEditor2#164]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
This is a request to be able to select between games and move through cues/sfx while a remix is playing. Though placing cues/sfx while a remix is playing should still be disabled.

### Steps to Reproduce the Problem
1. Play a remix
2. While remix is playing, try to select a game or move through the cues/sfx within a game.

**Expected behavior:** [insert what was supposed to happen here]
Be allowed to select between games/cues/sfx

**Actual behavior:** [insert what actually happened here]
Selecting is disabled, or "frozen."

**Version affected:** [insert the version of RHRE2 here]
2.15.2

### Additional Information
n/a

**Comment by chrislo27** [comment]
May I ask the reasoning for this? I am not opposed to it but I'd like to know why.

**Comment by Strawzzboy64** [comment]
Oops, I missed your question. Thank you for adding the feature.

It's a small difference, but it will make things slightly smoother for me. For some reason, even though I knew I couldn't select between games while a remix was playing, I kept trying to do so. I figured it might be something others do naturally too. Otherwise, I guess it's just a small thing for me. Thanks again!
