### ISSUE TITLE
Karate Man Wii "Hit three/four" cues are too quiet

### ISSUE THREAD

**Issue by Demirramon** [chrislo27/RhythmHeavenRemixEditor2#165]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
The cues "hit", "three" and "four" from Karate Man (Wii) sound way too quitet, to the point where I must stack four of them at the same time to make it sound like any other cue. However, the other voice cues and don't have this problem.

### Steps to Reproduce the Problem
1. Place a "hit three" or a "hit four" into the remix (or the cues individually, it doesn't matter).
2. Play the remix.

**Expected behavior:** I expected the cues to play at a similar volume to the other ones.

**Actual behavior:** The volume is extremelly low.

**Version affected:** v2.15.2 (but the problem is there from, at least, version v.2.13.x)

### Additional Information
I didn't notice any other cues with that problem. Also, as a side note (it should probably be made into a new issue but it's similar to this one), the "fish 4" cue from "Kitties!" sounds really weird and loud while in version v.2.13.X was fine.

**Comment by Miracle22s** [comment]
Hit 3 and 4 sound OK to me here.

**Comment by Demirramon** [comment]
Really? I've recorded the custom remix I was working on, there's two "hit three!" around 0:20 [here](https://instaud.io/private/4e28e08b8f65d60a7de7631d2b0eaf1bc6ef3970). If it only happens to me, I wonder what causes it.

**Comment by Miracle22s** [comment]
how about you turn up your volume?

**Comment by Miracle22s** [comment]
I mean by the music.

**Comment by Demirramon** [comment]
I don't think my volume is the problem, because if you listen to the track I linked in my last reply you can see how everything else sounds alright.

**Comment by chrislo27** [comment]
I listened to the audio files and they sound fine to me. I suspect that everything else is so "loud" that when it attempts to mix audio for the hit cues (possibly due to ordering?) it can't make it any "louder".

Have you tried lowering the volume of the music to see if it's a balancing issue?

**Comment by chrislo27** [comment]
This issue will be closed due to inactivity. If you find a solution/have more info feel free to reopen it.
