### ISSUE TITLE
Add Rap Women Sounds

### ISSUE THREAD

**Issue by Lvl100Feraligatr** [chrislo27/RhythmHeavenRemixEditor2#166]
### Prerequisites
* [✓] This issue specifically has something to do with RHRE2
* [N/A] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [✓] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [✓] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
Rap Men has it's own sounds, but Rap Women's are still unavalible.

### Steps to Reproduce the Problem
1. Look at Tengoku game list.
2. Notice Rap Women isn't there.

**Expected behavior:** Rap Women sounds are there.

**Actual behavior:** Rap Women sounds aren't there.

**Version affected:** 2.15.2

### Additional Information
This probably isn't of huge priority but they'd still be nice to have :]

**Comment by chrislo27** [comment]
You did not look for issues. See issue #156.

This issue will be closed. Do not attempt to reopen it.
