### ISSUE TITLE
The Power Calligraphy JSON files look ruined

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#170]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [X] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [X] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description ###
An internal glitch, but it is a glitch.

### Steps to Reproduce the Problem
Look at the Power Calligraphy JSON file. (GBA or Megamix)

**Expected behavior:** It should look normal.

**Actual behavior:** It looks like the picture you see below.
![capture](https://user-images.githubusercontent.com/25730122/27668266-ae2d4c02-5c45-11e7-9310-38c0e393d075.PNG)

**Version affected:** June 27th Snapshot B

**Comment by chrislo27** [comment]
Check your line separators. Microsoft Notepad is notorious for not supporting the correct linefeeds (we use LF for json files, and CRLF for source code).

http://i.imgur.com/QqIWfUV.png

**Comment by GuardedLolz** [comment]
How do I do that?

**Comment by chrislo27** [comment]
I'm not sure if you can change it in Notepad. I suggest using a more competent text editor like Notepad++.
