### ISSUE TITLE
Copy and Pasting in RHRE2?

### ISSUE THREAD

**Issue by iloveyouchrislo** [chrislo27/RhythmHeavenRemixEditor2#171]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
I was just wondering if it would be possible for copying and pasting to be added to RHRE2. It would be extremely helpful for copycat games like Working Dough and just be really convenient in general.

**Comment by chrislo27** [comment]
I implore you to read the readme, particularly the controls section.
https://github.com/chrislo27/RhythmHeavenRemixEditor2/wiki/The-README#controls

It states that copying can be achieved by the following:
```
Holding ALT while clicking on a selection will copy that selection
```

Please close this issue when you feel your question(s) have been answered.

**Comment by iloveyouchrislo** [comment]
Okay, thanks!
