### ISSUE TITLE
Pie charts on inspections general stats screen should be percentage of time used and not count

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#172]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [X] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [X] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
You can program the pie chart to show how much time each rhythm game takes up, rather than just how many cues it has. You can also program a setting that allows it to only show how much a rhythm game (all games, variations, and languages combined) takes up in total.

**Comment by chrislo27** [comment]
Please make better titles next time.
