### ISSUE TITLE
Rap Women needs to have better segmenting AND has offbeat patterns

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#173]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [X] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [X] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
Some cues are multiple syllables. This is bad. Furthermore, some of the patterns are wrong.

**Comment by chrislo27** [comment]
Fixed (by GuardedLolz) in commit `40ba72b`.
