### ISSUE TITLE
All patterns/cues should be named in English

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor2#177]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already
* [x] This is a REAL issue, reasonable feature consideration, or question, and not purely personal preference
* [x] I have filled out this issue template knowing if I remove it the issue will immediately become invalid and will be closed

### Description
All patterns and cues should be named in English. Example: kamone should be I suppose!, dokkoisho should be here we go!.

The exception to this rule is Tengoku because it was not localized. Example: Rap Men and Rap Women will not change.

**Version affected:** `v2.17.0-SNAPSHOT` (pre July 5)

**Comment by Miracle22s** [comment]
[dogNinjaMegamix.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/1125515/dogNinjaMegamix.zip)

**Comment by Miracle22s** [comment]
[dogNinjaEs.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/1125755/dogNinjaEs.zip)

**Comment by GuardedLolz** [comment]
I have one word: chadange.

**Comment by Miracle22s** [comment]
We need to redo those non-English texts to English, lolz.

**Comment by GuardedLolz** [comment]
You didn't put deprecations.

**Comment by Miracle22s** [comment]
That doesn't matter. Everything can do. It's to redo non-English texts.
