### ISSUE TITLE
Resizing windows does not work.

### ISSUE THREAD

**Issue by Sorurus** [chrislo27/RhythmHeavenRemixEditor2#47]
As of 2.2.2 you cannot resize windows. This is challenging for me, because the default resolution on my computer for some programs is small.

**Comment by chrislo27** [comment]
You have not been able to resize the window since the beginning. The game icons are set to be wrapped at a certain resolution (half of 1280) and will break on both higher and lower resolutions.

What is the resolution of your screen?
