### ISSUE TITLE
Fever Built to Scale 8 bounces pattern is incorrect

### ISSUE THREAD

**Issue by ToonLucas22** [chrislo27/RhythmHeavenRemixEditor2#65]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Title explains it. 8 bounces pattern is actually incorrect.

### Steps to Reproduce
1. Place the 8 bounces pattern
2. Take a close listen.

...

**Expected behavior:** Pattern should go "* A * * * A * SHOOT*

**Actual behavior:** Instead it goes "* A * A * * * SHOOT*

**Version affected:** v2.3.4, dunno about other versions.

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by chrislo27** [comment]
Thank you, fixed for v2.4.6 (next update).
