### ISSUE TITLE
saving issue

### ISSUE THREAD

**Issue by boloholic** [chrislo27/RhythmHeavenRemixEditor2#67]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
it just,, doesn't save? i saved 5 times and the file just,,,, doesn't exist anymore. all the progress nukes itself. even the backup autosave files don't work.

### Steps to Reproduce
1. make something
2. save
3. reopen
...

**Expected behavior:** [What was supposed to happen]
The progress should've been saved
**Actual behavior:** [What actually happened]
The progress is _gone_
**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of RHRE2]
Version 2.3.5
### Additional Information
Sorry for the inconvenience ;;

**Comment by chrislo27** [comment]
Please provide a stacktrace. That is, go into the command prompt/terminal and copy everything starting from `java -jar RHRE.jar`.

**Comment by ToonLucas22** [comment]
Not sure whether this is related to the issue, but BRHRE files don't open in RHRE2 for whatever reason. I have to use the deprecated RHRE2 files instead.

**Comment by chrislo27** [comment]
No help without a stacktrace. Open a new issue instead please. Saying "for whatever reason" doesn't help - sure, you don't know what the reason is, but I need evidence that it doesn't work so I can work out *why*.

Did you just rename the file extension? That *definitely* doesn't work because their file structures are entirely different.

**Comment by boloholic** [comment]
Sorry for responding so late. I got caught up in school and other things,
then i had to figure out what a stacktrace was, (i'm a simple girl i don't
know much about applications) and from what i understand, i didn't recieve
one. It just says that it has saved, but when i reopen the remix, the
entire thing is gone.
Sorry that if i didn't help all too much.

**Comment by chrislo27** [comment]
I just released `v2.5.2` which automatically saves your console to a file in the `logs/` folder. Run the program, try to load the file, and upload that file here or to Pastebin. Also, please upload the rhre2 file here (or to Pastebin) as well.

https://github.com/chrislo27/RhythmHeavenRemixEditor2/releases/tag/v2.5.2

**Comment by boloholic** [comment]
Though I didn't follow your instructions thuroughly, I DID make an entire
custom remix, save it, and was able to retrieve it, when attempting
to.Thanks for your help, it's much appreciated!
