### ISSUE TITLE
crashes while loading a remix.

### ISSUE THREAD

**Issue by Armodillomatt12** [chrislo27/RhythmHeavenRemixEditor2#69]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
it even happens when it's loading the same version as the release. Ex. loading remix made in v2.4.1 but the app exits out when remix is loaded.

### Steps to Reproduce
1. Open the app
2. Load a RHRE2 file
3. I might fail.
...

**Expected behavior:** [What was supposed to happen]
load remix
**Actual behavior:** [What actually happened]
exits out
**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of RHRE2]
RHRE2 v2.4.1
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by chrislo27** [comment]
Can you put the console logs into Pastebin and put it here?
