### ISSUE TITLE
Sick Beats Audio echo

### ISSUE THREAD

**Issue by aandroidd** [chrislo27/RhythmHeavenRemixEditor2#70]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Occasionally, with the "Sick beats" minigame sfx when using "Quick" versions of blue and pink viruses or the independent appear and kill sfx, the sounds will "echo" and double up even though only one sfx is present. I have experienced this bug with 150 BPM at beats ~157-172. Attempts at this stage have not been made to recreate the bug at other BPMs or beat locations
Using v2.4.2 WITHOUT loading all sounds.
https://drive.google.com/file/d/0B5uC8HNRqaNVWUl1czdyMWw4aFE/view

### Steps to Reproduce the Problem
1. Place sfx as normal
2. Play section

**Expected behavior:** Sound plays normally

**Actual behavior:** Sound echoes

**Stacktrace/error log:** [copy the console output, put it on Pastebin or Hastebin, and put the link here]

**Version affected:** 2.4.2 WITHOUT load all sounds

**Comment by chrislo27** [comment]
Fixed for next version (whoosh sfx had the stab and kill sfx too??).
