### ISSUE TITLE
Toss Boys Cue defaults to another Toss Boys cue when reloading the remix

### ISSUE THREAD

**Issue by Strawzzboy64** [chrislo27/RhythmHeavenRemixEditor2#72]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
the Toss Boys Cue "Ao-kun Super to Kii-yan" is replaced with "Ao-kun Super to Aka-chan" when loading a remix after saving.

### Steps to Reproduce the Problem
1. Place the Toss Boys cue "Ao-kun Super to Kii-yan"
2. Save the remix (as a bhre file)
3. Close the editor
4. Open the editor again and load the remix

**Expected behavior:** [insert what was supposed to happen here]
The "Ao-kun Super to Kii-yan" cue should remain the same
**Actual behavior:** [insert what actually happened here]
The "Ao-kun Super to Kii-yan" cue is replaced with the "Ao-kun Super to Aka-chan" cue

**Stacktrace/error log:** [copy the console output, put it on Pastebin or Hastebin, and put the link here]

**Version affected:** [insert the version of RHRE2 here]
RHRE 2.5.0

### Additional Information
[insert any other information that may be able to help me with the problem here]

**Comment by chrislo27** [comment]
Fixed - will test later tonight to confirm it works.
