### ISSUE TITLE
How do you create or edit a palette in RHRE2?

### ISSUE THREAD

**Issue by Armodillomatt12** [chrislo27/RhythmHeavenRemixEditor2#86]
I need help.
This is what i have so far.

![asdfghjkl](https://cloud.githubusercontent.com/assets/25271478/23871633/a085d97c-0801-11e7-93e0-50534ed3c21a.PNG)

**Comment by chrislo27** [comment]
The editor will not load example.json as it is identical to the white palette. Rename the file, put it in the same folder. Close this issue if that solves your problem.

Next time, please include more data and fill out the template with the version, etc. It helps me debug it more easily if this is a inherent problem and not human error. Not filling out the template only makes it harder to communicate back and forth.

**Comment by Armodillomatt12** [comment]
it worked!
and sorry
