### ISSUE TITLE
Editor Crashes Whenever I try to use Custom Sounds 

### ISSUE THREAD

**Issue by AnonUserGuy** [chrislo27/RhythmHeavenRemixEditor2#88]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
The editor will crash whenever I try to drag one of the custom sound effects into the staff.

### Steps to Reproduce the Problem
1. Set up a custom sound effects in the customSounds editor. The game is called "Other" and there are to ~2 second long sound effects, called "here we" and "go".
2. Attempt to drag either sound onto the staff.

**Expected behavior:** The sound appear in the staff like any other sound effect.

**Actual behavior:** The editor crashes as soon as the sound is clicked. 

**Stacktrace/error log:** (https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/853442/log_2017-03-19_01-01-44.txt)

**Version affected:** v2.8.3

### Additional Information
- Here are the files if needed: 
[the files.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/853449/the.files.zip)

- I considered going the other route and creating a data.json and stuff, but I have no idea where this is supposed to go or how it should be formatted. One tutorial mentions an assets folder, but I can't find said folder. All I have is the customSounds, logs, palettes, and crash folders.

- Here's a video of it if needed: 
[video.zip](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/853456/video.zip)

**Comment by AnonUserGuy** [comment]
Also, this is unrelated to the bug mentioned prior, but the homerun sound effect for Exhibition Match pitch changed with the tempo. Same version.

**Comment by chrislo27** [comment]
Your sound files are too big (loaded sound data must be under a megabyte). Trim the sounds and use ogg format. I'll add a note in the SFX readme about this.

As for the Exhibition Match thing - I think that's intended but I'll change it to not auto pitch.

**Comment by AnonUserGuy** [comment]
Ok thanks.
