### ISSUE TITLE
[Minor bug] RHRE UI scaling messes up slightly when maximizing while loading

### ISSUE THREAD

**Issue by Arctiiq** [chrislo27/RhythmHeavenRemixEditor2#89]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [ ] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
When you maximize the window while the application is loading, the scaling of the UI during the loading will move to the bottom right

### Steps to Reproduce the Problem
1. Double click on the application to load it
2. While it's loading (when it shows the Remix Editor logo) click on the "maximize window" button on the top right

**Expected behavior:** [insert what was supposed to happen here]
The window should scale normally and the loading UI should be in the middle.

**Actual behavior:** [insert what actually happened here]
The UI gets shifted to the bottom right slightly, when the application finishes loading, it reverts back to the window size it started in.

**Stacktrace/error log:** [attach the log file from `logs/log_YYYY-MM-DD_HH-MM-SS.txt here]
http://pastebin.com/akHxCsf8

**Version affected:** [insert the version of RHRE2 here]
v2.8.3

### Additional Information
[insert any other information that may be able to help me with the problem here]

**Comment by chrislo27** [comment]
Fixed for v2.9.0.
