### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by GuardedLolz** [chrislo27/RhythmHeavenRemixEditor2#91]
### Prerequisites
* [X] This issue specifically has something to do with RHRE2
* [X] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Whenever I try to use this json, I get an ExceptionInInitializer error.

### Steps to Reproduce the Problem
1. Put this json, its sounds, and its icon in the editor.
2. Run the editor.

**Expected behavior:** The game should run.

**Actual behavior:** I get an error.

**Stacktrace/error log:** [log_2017-03-23_10-21-41.txt](https://github.com/chrislo27/RhythmHeavenRemixEditor2/files/865226/log_2017-03-23_10-21-41.txt)

**Version affected:** 2.9

BTW, expect a really big pull request sometime in mid-April.

Here's the data file I used: (WARNING: LONG!!!)

{
  "gameID": "animalAcrobat",
  "name": "Animal Acrobat",
  "series": "megamix",
  "cues": [
    {
      "id": "animalAcrobat/start",
      "duration": 1.0,
      "name": "start"
    },
    {
      "id": "animalAcrobat/ready",
      "duration": 1.0,
      "name": "ready"
    },
    {
      "id": "animalAcrobat/grab",
      "duration": 1.0,
      "name": "monkey - grab"
    },
    {
      "id": "animalAcrobat/shout",
      "duration": 1.0,
      "name": "monkey - shout"
    },
    {
      "id": "animalAcrobat/elephantClear",
      "duration": 1.0,
      "name": "elephant - clear"
    },
    {
      "id": "animalAcrobat/giraffeClear1",
      "duration": 2.0,
      "baseBpm": 135,
      "name": "giraffe - drumroll"
    },
    {
      "id": "animalAcrobat/giraffeClear2",
      "duration": 1.0,
      "name": "giraffe - ring of fire"
    }
  ],
  "patterns": [
    {
      "id": "animalAcrobat_elephant",
      "name": "elephant",
      "cues": [
        {
          "id": "animalAcrobat/grab",
          "track": 1,
          "beat": 0.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 0.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 1.0
        },
        {
          "id": "animalAcrobat/elephantClear",
          "beat": 2.0
        }
      ]
    },
    {
      "id": "animalAcrobat_giraffe",
      "name": "giraffe",
      "cues": [
        {
          "id": "animalAcrobat/grab",
          "beat": 0.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 2.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 3.0
        },
        {
          "id": "animalAcrobat/giraffeClear1",
          "beat": 4.0
        },
        {
          "id": "animalAcrobat/giraffeClear2",
          "beat": 5.0
        }
      ]
    },
    {
      "id": "animalAcrobat_whiteMonkey",
      "name": "white monkey",
      "cues": [
        {
          "id": "animalAcrobat/grab",
          "beat": 0.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 1.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 2.0
        },
        {
          "id": "animalAcrobat/elephantClear",
          "beat": 3.0
        },
        {
          "id": "animalAcrobat/ready",
          "track": 1,
          "beat": 4.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 4.0
        },
        {
          "id": "animalAcrobat/grab",
          "track": 1,
          "beat": 5.0
        },
        {
          "id": "animalAcrobat/shout",
          "beat": 5.0
        },
        {
          "id": "animalAcrobat/elephantClear",
          "beat": 6.0
        }
      ]
    }
  ]
}

It wasn't flat when I copy-pasted it.

**Comment by chrislo27** [comment]
It's `gameName`, not `name`. 

Also, the title of "Help me." is not very descriptive.
