### ISSUE TITLE
Inspections are lacking and should be removed

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/RhythmHeavenRemixEditor2#93]
Inspections are... lacking to say the least. They were a feature first added in `v2.2.0` but have gotten no updates to date. It is not very useful because of how few games it supports, and suffers from the manual code editing problem that RHRE0 had when adding new games.

So, I would like to remove them. Personally, I do not use them at all because the scope it covers is so limited. 

**Because the vote is leaning towards remove, I will default them to being off, and provide a warning if they are used. They will be removed not in `v2.10.0` but in `v2.11.0`.**

**React to this post with either :+1: or :-1: indicating if you would like to keep or remove inspections respectively. The action will take place for v2.10.0.**

**Comment by Sorurus** [comment]
They feel rude to me like you do something wrong for one second because you're organizing or something and it's like STOP AT ONCE YOU FOOL YOU HAVENT EVEN PLAYED THIS GAME GRRRR

**Comment by chrislo27** [comment]
Yeah, I feel like I've gotten desensitized to them when I first added them because I based them off inspections in IntelliJ IDEA (my IDE/code editor) where if you miss something you're INVALID AND WRONG AND TRY HARDER.

Thanks for the feedback!

**Comment by GuardedLolz** [comment]
Yeah. All I think you need to do is to IMPROVE, not REMOVE.

**Comment by chrislo27** [comment]
Problem with this is that I do not have time to retroactively fix it. Ideally it should be in json but finding a common pattern to implement is unfeasible.

Thank you for the input.

**Comment by Sorurus** [comment]
Also there's no inspection for keep the beat games, but it would take a while making sure every keep the beat pattern has no inspection if the last game is a keep the beat game and needing to do it for every startin

**Comment by chrislo27** [comment]
Because the vote is leaning towards remove, I will leave them in but default them to off and have a deprecation warning if they are used.
